apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:
      - name: ecr-secret 
      containers:
      - name: python-app
        image: 536697266753.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
        ports:
        - containerPort: 5000
