apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 975050176026.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest  
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-secret
