- hosts: jenkins-instance
  become: true
  gather_facts: true
  roles:
    - docker_setup
    - jenkins_setup

- hosts: k3s-instance
  become: true
  gather_facts: true
  roles:
    - helm_setup  

- hosts: k3s-instance
  gather_facts: true
  roles:
    - nginx_setup